version: '3.9'

services:
  api:
    build: .
    container_name: python-garmin-api-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
